services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Auto-publish.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
